### ISSUE TITLE
Get Current Connections

### ISSUE THREAD

**Issue by VILATTI** [starfish-codes/sf-control#11]
Connections are the project specific link of a time-reporting tool and respective reporting setup there with an assignment at Starfish.team.

```
sfctl time connections get
```

This will list all known connections in that project. The data is read from the `.sflink` file.

```
Connection: [ASSIGNMENT NAME]
  provider: toggl
  workspace_id: 54321
  project_ids: 123, 324,23, 333
  task_ids:
  billable: both
  rounding: off

[MORE CONNECTIONS]
```
